// Generated by scripts/locgen.mjs. Holds the shipped language's translation
// table for a per-language build. In this default state it
// assigns nothing: the runtime falls back to the source strings, so an
// ordinary build produces the source-string (English) image with no
// localization tooling involved.
//
// This file exists, and is listed first in pxt.json "files", for three
// reasons:
//   - every file listed in pxt.json must exist for the build to succeed;
//   - its assignments must run before any other app file initializes, because
//     some controls capture the default font at construction time; keeping
//     the entry and this placeholder committed pins that ordering statically;
//   - with nothing assigned, the vanilla build is the source-string build.
//
// Non-default states are transient build intermediates: locgen writes a
// language's table, builds, and restores this default state afterward. Only
// the default state belongs in a commit. After a failed language build,
// locgen leaves the generated table in place for debugging; restore it by
// rerunning locgen or reverting this file.
