// auto-generated, run 'node scripts/lochex.mjs' to refresh
namespace microcode {
    const toLower = (s: string) => s ? s.toLowerCase() : s;
    export function reverseTooltip(text: string): string {
        let res: string = ""
        if (!text) return text;
        else if (toLower(text) === toLower("for micro:bit V2")) res = "tagline";
        else if (toLower(text) === toLower("when...")) res = "sensors";
        else if (toLower(text) === toLower("do...")) res = "actuators";
        else if (toLower(text) === toLower("when")) res = "when";
        else if (toLower(text) === toLower("do")) res = "do";
        else if (toLower(text) === toLower("connect")) res = "connect";
        else if (toLower(text) === toLower("page start")) res = "S1";
        else if (toLower(text) === toLower("press")) res = "S2";
        else if (toLower(text) === toLower("release")) res = "S2B";
        else if (toLower(text) === toLower("move")) res = "S3";
        else if (toLower(text) === toLower("timer")) res = "S4";
        else if (toLower(text) === toLower("light")) res = "S5";
        else if (toLower(text) === toLower("temperature")) res = "S6";
        else if (toLower(text) === toLower("radio receive")) res = "S7";
        else if (toLower(text) === toLower("hear")) res = "S8";
        else if (toLower(text) === toLower("variable X set")) res = "S9A";
        else if (toLower(text) === toLower("variable Y set")) res = "S9B";
        else if (toLower(text) === toLower("variable Z set")) res = "S9C";
        else if (toLower(text) === toLower("magnet")) res = "S10";
        else if (toLower(text) === toLower("slider")) res = "S11";
        else if (toLower(text) === toLower("dial")) res = "S12";
        else if (toLower(text) === toLower("moisture")) res = "S16";
        else if (toLower(text) === toLower("distance")) res = "S17";
        else if (toLower(text) === toLower("line")) res = "S18";
        else if (toLower(text) === toLower("rule")) res = "rule";
        else if (toLower(text) === toLower("add rule")) res = "add_rule";
        else if (toLower(text) === toLower("delete rule")) res = "delete_rule";
        else if (toLower(text) === toLower("equals")) res = "arith_equals";
        else if (toLower(text) === toLower("plus")) res = "arith_plus";
        else if (toLower(text) === toLower("save")) res = "disk";
        else if (toLower(text) === toLower("load")) res = "load";
        else if (toLower(text) === toLower("touch pin 0")) res = "F0";
        else if (toLower(text) === toLower("touch pin 1")) res = "F1";
        else if (toLower(text) === toLower("touch pin 2")) res = "F2";
        else if (toLower(text) === toLower("button A")) res = "F3";
        else if (toLower(text) === toLower("button B")) res = "F4";
        else if (toLower(text) === toLower("key 1")) res = "F5";
        else if (toLower(text) === toLower("key 2")) res = "F6";
        else if (toLower(text) === toLower("logo")) res = "F7";
        else if (toLower(text) === toLower("1")) res = "F8";
        else if (toLower(text) === toLower("2")) res = "F9";
        else if (toLower(text) === toLower("3")) res = "F10";
        else if (toLower(text) === toLower("4")) res = "F11";
        else if (toLower(text) === toLower("5")) res = "F12";
        else if (toLower(text) === toLower("1/4 second")) res = "F13";
        else if (toLower(text) === toLower("1 second")) res = "F14";
        else if (toLower(text) === toLower("1 random second")) res = "F18";
        else if (toLower(text) === toLower("5 seconds")) res = "F19";
        else if (toLower(text) === toLower("loud")) res = "F15";
        else if (toLower(text) === toLower("quiet")) res = "F16";
        else if (toLower(text) === toLower("shake")) res = "F17_shake";
        else if (toLower(text) === toLower("tilt up")) res = "F17_tilt_up";
        else if (toLower(text) === toLower("tilt down")) res = "F17_tilt_down";
        else if (toLower(text) === toLower("tilt left")) res = "F17_tilt_left";
        else if (toLower(text) === toLower("tilt right")) res = "F17_tilt_right";
        else if (toLower(text) === toLower("face up")) res = "F17_face_up";
        else if (toLower(text) === toLower("face down")) res = "F17_face_down";
        else if (toLower(text) === toLower("variable X")) res = "F20A";
        else if (toLower(text) === toLower("variable Y")) res = "F20B";
        else if (toLower(text) === toLower("variable Z")) res = "F20C";
        else if (toLower(text) === toLower("turn left")) res = "F21L";
        else if (toLower(text) === toLower("turn right")) res = "F21R";
        else if (toLower(text) === toLower("warmer")) res = "F22U";
        else if (toLower(text) === toLower("colder")) res = "F22D";
        else if (toLower(text) === toLower("edit")) res = "C0";
        else if (toLower(text) === toLower("samples")) res = "C1";
        else if (toLower(text) === toLower("switch page")) res = "A1";
        else if (toLower(text) === toLower("play sound")) res = "A2";
        else if (toLower(text) === toLower("microphone")) res = "A3";
        else if (toLower(text) === toLower("music")) res = "A4";
        else if (toLower(text) === toLower("show image")) res = "A5";
        else if (toLower(text) === toLower("radio send")) res = "A6";
        else if (toLower(text) === toLower("radio set group")) res = "A6A";
        else if (toLower(text) === toLower("random number")) res = "A7";
        else if (toLower(text) === toLower("show number")) res = "A10";
        else if (toLower(text) === toLower("page 1")) res = "M1";
        else if (toLower(text) === toLower("page 2")) res = "M2";
        else if (toLower(text) === toLower("page 3")) res = "M3";
        else if (toLower(text) === toLower("page 4")) res = "M4";
        else if (toLower(text) === toLower("page 5")) res = "M5";
        else if (toLower(text) === toLower("1")) res = "M6";
        else if (toLower(text) === toLower("2")) res = "M7";
        else if (toLower(text) === toLower("3")) res = "M8";
        else if (toLower(text) === toLower("4")) res = "M9";
        else if (toLower(text) === toLower("5")) res = "M10";
        else if (toLower(text) === toLower("LED image")) res = "M15";
        else if (toLower(text) === toLower("music")) res = "M18";
        else if (toLower(text) === toLower("giggle")) res = "M19giggle";
        else if (toLower(text) === toLower("happy")) res = "M19happy";
        else if (toLower(text) === toLower("hello")) res = "M19hello";
        else if (toLower(text) === toLower("mysterious")) res = "M19mysterious";
        else if (toLower(text) === toLower("sad")) res = "M19sad";
        else if (toLower(text) === toLower("slide")) res = "M19slide";
        else if (toLower(text) === toLower("soaring")) res = "M19soaring";
        else if (toLower(text) === toLower("spring")) res = "M19spring";
        else if (toLower(text) === toLower("twinkle")) res = "M19twinkle";
        else if (toLower(text) === toLower("yawn")) res = "M19yawn";
        else if (toLower(text) === toLower("variable X")) res = "M20A";
        else if (toLower(text) === toLower("variable Y")) res = "M20B";
        else if (toLower(text) === toLower("variable Z")) res = "M20C";
        else if (toLower(text) === toLower("radio value")) res = "M21";
        else if (toLower(text) === toLower("dice")) res = "M22";
        else if (toLower(text) === toLower("repeat")) res = "M23";
        else if (toLower(text) === toLower("melody")) res = "M24";
        else if (toLower(text) === toLower("temperature")) res = "M25";
        else if (toLower(text) === toLower("LED")) res = "A8";
        else if (toLower(text) === toLower("set variable X")) res = "A9A";
        else if (toLower(text) === toLower("set variable Y")) res = "A9B";
        else if (toLower(text) === toLower("set variable Z")) res = "A9C";
        else if (toLower(text) === toLower("red")) res = "A20_1";
        else if (toLower(text) === toLower("green")) res = "A20_2";
        else if (toLower(text) === toLower("blue")) res = "A20_3";
        else if (toLower(text) === toLower("purple")) res = "A20_4";
        else if (toLower(text) === toLower("yellow")) res = "A20_5";
        else if (toLower(text) === toLower("black")) res = "A20_6";
        else if (toLower(text) === toLower("rainbow")) res = "A20_rainbow";
        else if (toLower(text) === toLower("sparkle")) res = "A20_sparkle";
        else if (toLower(text) === toLower("servo set angle")) res = "A21_";
        else if (toLower(text) === toLower("relay")) res = "A22";
        else if (toLower(text) === toLower("servo power")) res = "A23";
        else if (toLower(text) === toLower("LED {x} {y} {state}")) res = "SR_LED";
        else if (toLower(text) === toLower("note {index} {state}")) res = "SR_NOTE";
        else if (toLower(text) === toLower("on")) res = "SR_ON";
        else if (toLower(text) === toLower("off")) res = "SR_OFF";
        else if (toLower(text) === toLower("on")) res = "M26";
        else if (toLower(text) === toLower("off")) res = "M27";
        else if (toLower(text) === toLower("on")) res = "F24";
        else if (toLower(text) === toLower("off")) res = "F25";
        else if (toLower(text) === toLower("robot")) res = "CAR";
        else if (toLower(text) === toLower("forward")) res = "CAR1";
        else if (toLower(text) === toLower("reverse")) res = "CAR2";
        else if (toLower(text) === toLower("turn left")) res = "CAR3";
        else if (toLower(text) === toLower("turn right")) res = "CAR4";
        else if (toLower(text) === toLower("stop")) res = "CAR5";
        else if (toLower(text) === toLower("fast forward")) res = "CAR6";
        else if (toLower(text) === toLower("spin left")) res = "CAR7";
        else if (toLower(text) === toLower("spin right")) res = "CAR8";
        else if (toLower(text) === toLower("LED red")) res = "CAR9";
        else if (toLower(text) === toLower("LED green")) res = "CAR10";
        else if (toLower(text) === toLower("LED blue")) res = "CAR11";
        else if (toLower(text) === toLower("LED OFF")) res = "CAR12";
        else if (toLower(text) === toLower("arm open")) res = "CAR13";
        else if (toLower(text) === toLower("arm close")) res = "CAR14";
        else if (toLower(text) === toLower("wall")) res = "S13";
        else if (toLower(text) === toLower("line")) res = "S14";
        else if (toLower(text) === toLower("light")) res = "S15";
        else if (toLower(text) === toLower("left")) res = "F23L";
        else if (toLower(text) === toLower("right")) res = "F23R";
        else if (toLower(text) === toLower("both")) res = "F23B";
        else if (toLower(text) === toLower("none")) res = "F23N";
        else if (toLower(text) === toLower("lost left")) res = "F23NL";
        else if (toLower(text) === toLower("lost right")) res = "F23NR";        
        return res;
    }
}