// Per-language localization build for microcode-v2.
//
// A thin wrapper over the shared loc tooling in @microbit-apps/ui-core. It
// supplies the app-specific pieces the generic tool does not know about:
//   - the tooltip source strings as extra coverage inventory (minus the N*
//     sample ids, which ship only to the web);
//   - the sample-only table exclusion (those N* source strings never occupy
//     device flash);
//   - the tagline as a small-font (font5) context string;
//   - the web snapshot side output (assets/strings/<lang>/tooltips.json);
//   - the microcode-v2.<lang>.hex naming and the committed loc.g.ts default.
//
// Usage:
//   node scripts/locgen.mjs [lang ...]              build per-language hexes
//   node scripts/locgen.mjs --coverage [--verbose] [lang ...]
//   Flags: --keep leaves the last generated loc.g.ts in place.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"
import { runLocGen } from "@microbit-apps/ui-core/loc"

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const TOOLTIPS = join(ROOT, "locales", "tooltips.json")

// The committed default state of loc.g.ts: assigns nothing, so the vanilla
// build ships the source strings. Listed first in pxt.json "files" so its
// assignments run before controls capture the default font at construction.
const DEFAULT_LOC_G = `// Generated by scripts/locgen.mjs. Holds the shipped language's translation
// table for a per-language build. In this default state it
// assigns nothing: the runtime falls back to the source strings, so an
// ordinary build produces the source-string (English) image with no
// localization tooling involved.
//
// This file exists, and is listed first in pxt.json "files", for three
// reasons:
//   - every file listed in pxt.json must exist for the build to succeed;
//   - its assignments must run before any other app file initializes, because
//     some controls capture the default font at construction time; keeping
//     the entry and this placeholder committed pins that ordering statically;
//   - with nothing assigned, the vanilla build is the source-string build.
//
// Non-default states are transient build intermediates: locgen writes a
// language's table, builds, and restores this default state afterward. Only
// the default state belongs in a commit. After a failed language build,
// locgen leaves the generated table in place for debugging; restore it by
// rerunning locgen or reverting this file.
`

// The id-keyed tooltip master (id -> source string), in file order.
const tooltipMaster = () => JSON.parse(readFileSync(TOOLTIPS, "utf8"))

// Source strings that appear only under N* sample ids. They surface on the web
// gallery; the device never resolves them, so they are excluded from device
// tables.
function sampleOnlySources() {
    const master = tooltipMaster()
    const sample = new Set()
    const other = new Set()
    for (const id of Object.keys(master)) {
        if (/^N\d+$/.test(id)) sample.add(master[id])
        else other.add(master[id])
    }
    for (const src of other) sample.delete(src)
    return sample
}

// Write the web surface's id-keyed strings file for a language. For the source
// language every id maps to its source string; otherwise the ids whose source
// string has an entry in the merged catalog.
function writeWebStrings(lang, merged) {
    const master = tooltipMaster()
    const out = {}
    for (const id of Object.keys(master)) {
        const src = master[id]
        if (merged === null) out[id] = src
        else if (merged[src] !== undefined) out[id] = merged[src]
    }
    const dir = join(ROOT, "assets", "strings", lang)
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
    writeFileSync(join(dir, "tooltips.json"), JSON.stringify(out, null, 4) + "\n")
    console.log(`  web strings: assets/strings/${lang}/tooltips.json (${Object.keys(out).length} ids)`)
}

const argv = process.argv.slice(2)
const positional = argv.filter(a => !a.startsWith("--"))

runLocGen(
    {
        root: ROOT,
        coverage: argv.indexOf("--coverage") >= 0,
        verbose: argv.indexOf("--verbose") >= 0,
        keep: argv.indexOf("--keep") >= 0,
        defaultLocG: DEFAULT_LOC_G,
        reservedLangNames: ["tooltips"],
        hexName: lang => `microcode-v2.${lang}.hex`,
        exclude: { label: "sample-only", keys: () => sampleOnlySources() },
        smallFontContext: {
            font: "font5",
            strings: () => {
                const tips = tooltipMaster()
                return tips["tagline"] ? [tips["tagline"]] : []
            },
        },
        extraInventory: [
            {
                path: TOOLTIPS,
                mapper: tips =>
                    Object.keys(tips)
                        .filter(id => !/^N\d+$/.test(id))
                        .map(id => tips[id]),
            },
        ],
        postMerge: writeWebStrings,
    },
    positional,
)
