// Per-language localization build generator.
//
// For each requested language: merge the ui-core, ui-controls and app
// translation catalogs, drop identity and unrenderable entries, emit
// loc.g.ts, build with mkc, and copy the resulting hex to
// assets/hex/microcode-v2.<lang>.hex. A language with no renderable
// translations builds no hex. loc.g.ts is restored to its default
// (assign-nothing) state after the run.
//
// Every requested language (hex or not, including "en") also gets its web
// snapshot regenerated: the deployed web page fetches the id-keyed
// assets/strings/<lang>/tooltips.json at runtime, so locgen derives those
// files from the merged catalog. The browser supplies its own fonts, so web
// snapshots are not glyph-validated and include entries the device drops.
//
// Usage: node scripts/locgen.mjs [lang ...]
//   No args: "en" plus every locales/<lang>.json (excluding en and tooltips).
//   Args:    only the named languages ("en" allowed).
//
// Coverage: node scripts/locgen.mjs --coverage [--verbose] [lang ...]
//   Reports, per language, how much of the source-string inventory the merged
//   catalog translates. Builds nothing and does not write loc.g.ts. No args:
//   every locales/<lang>.json except en and tooltips. --verbose lists the
//   missing source strings.

import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync, copyFileSync, statSync } from "fs";
import { execSync } from "child_process";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = dirname(SCRIPT_DIR);

// loc.g.ts default state: header comment and no code, so the runtime falls
// back to the source strings.
const DEFAULT_LOC_G = `// Generated by scripts/locgen.mjs. Holds the shipped language's translation
// table for a per-language build. In this default state it
// assigns nothing: the runtime falls back to the source strings, so an
// ordinary build produces the source-string (English) image with no
// localization tooling involved.
//
// This file exists, and is listed first in pxt.json "files", for three
// reasons:
//   - every file listed in pxt.json must exist for the build to succeed;
//   - its assignments must run before any other app file initializes, because
//     some controls capture the default font at construction time; keeping
//     the entry and this placeholder committed pins that ordering statically;
//   - with nothing assigned, the vanilla build is the source-string build.
//
// Non-default states are transient build intermediates: locgen writes a
// language's table, builds, and restores this default state afterward. Only
// the default state belongs in a commit. After a failed language build,
// locgen leaves the generated table in place for debugging; restore it by
// rerunning locgen or reverting this file.
`;

const LOC_G_PATH = join(ROOT, "loc.g.ts");
const HEX_DIR = join(ROOT, "assets", "hex");

// --- font glyph tables ------------------------------------------------------

// font8: 6x8 glyphs in a hex literal in display-shield/text.ts. Each record is
// 8 bytes: 2-byte little-endian codepoint then 6 data bytes.
function parseFont8Coverage() {
    const src = readFileSync(join(ROOT, "pxt_modules", "display-shield", "text.ts"), "utf8");
    const m = src.match(/font8[\s\S]*?data:\s*hex`([\s\S]*?)`/);
    if (!m) throw new Error("could not locate font8 hex literal in display-shield/text.ts");
    const hex = m[1].replace(/\s+/g, "");
    const set = new Set();
    for (let i = 0; i + 16 <= hex.length; i += 16) {
        const lo = parseInt(hex.slice(i, i + 2), 16);
        const hi = parseInt(hex.slice(i + 2, i + 4), 16);
        set.add(lo | (hi << 8));
    }
    return set;
}

// font5: 6x5 glyphs in a hex literal in display-shield/text.ts. Records are
// 8 bytes: 2-byte little-endian codepoint then 6 data bytes (charSize
// ((5+7)>>3)*6 = 6). font5 covers Latin only.
function parseFont5Coverage() {
    const src = readFileSync(join(ROOT, "pxt_modules", "display-shield", "text.ts"), "utf8");
    const m = src.match(/font5[\s\S]*?data:\s*hex`([\s\S]*?)`/);
    if (!m) throw new Error("could not locate font5 hex literal in display-shield/text.ts");
    const hex = m[1].replace(/\s+/g, "");
    const set = new Set();
    for (let i = 0; i + 16 <= hex.length; i += 16) {
        const lo = parseInt(hex.slice(i, i + 2), 16);
        const hi = parseInt(hex.slice(i + 2, i + 4), 16);
        set.add(lo | (hi << 8));
    }
    return set;
}

let _font5Cov = null;
let _font8Cov = null;
function font5Coverage() {
    if (!_font5Cov) _font5Cov = parseFont5Coverage();
    return _font5Cov;
}
function font8Coverage() {
    if (!_font8Cov) _font8Cov = parseFont8Coverage();
    return _font8Cov;
}

// Source strings the app renders in a font5 (small, Latin-only) context. Their
// translations are validated against font5 coverage rather than the build
// font: a translation font5 cannot render would draw blank, so it is dropped
// and the runtime falls back to the source string. Today the only such string
// is the home-screen tagline: screens/home.ts draws assets.getText("tagline")
// (which resolves to ui.loc(<tagline source>)) with bitmaps.font5.
function font5SrcStrings() {
    const tips = readCatalog(join(ROOT, "locales", "tooltips.json"));
    const set = new Set();
    if (tips && tips["tagline"]) set.add(tips["tagline"]);
    return set;
}

// Master tooltip map (id -> source string), in file order.
let _tooltipMaster = null;
function tooltipMaster() {
    if (!_tooltipMaster)
        _tooltipMaster = readCatalog(join(ROOT, "locales", "tooltips.json")) || {};
    return _tooltipMaster;
}

// Source strings that appear only under N* sample ids. They surface on the
// web page's gallery; the device never resolves them, so they are excluded
// from device tables.
function sampleOnlySources() {
    const master = tooltipMaster();
    const sample = new Set();
    const other = new Set();
    for (const id of Object.keys(master)) {
        if (/^N\d+$/.test(id)) sample.add(master[id]);
        else other.add(master[id]);
    }
    for (const src of other) sample.delete(src);
    return sample;
}

// Write the web surface's id-keyed strings file for a language. For "en"
// every id maps to its source string; otherwise the ids whose source string
// has an entry in the merged catalog. Returns the emitted id count.
function writeWebStrings(lang, merged) {
    const master = tooltipMaster();
    const out = {};
    for (const id of Object.keys(master)) {
        const src = master[id];
        if (lang === "en") out[id] = src;
        else if (merged[src] !== undefined) out[id] = merged[src];
    }
    const dir = join(ROOT, "assets", "strings", lang);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "tooltips.json"), JSON.stringify(out, null, 4) + "\n");
    return Object.keys(out).length;
}

// --- helpers ----------------------------------------------------------------

function toHexCp(cp) {
    return "U+" + cp.toString(16).toUpperCase().padStart(4, "0");
}

function readCatalog(path) {
    if (!existsSync(path)) return null;
    return JSON.parse(readFileSync(path, "utf8"));
}

// The ordered translation catalog layers for a language: ui-core, then
// ui-controls, then the app. Later layers override earlier ones on merge.
function layerPathsFor(lang) {
    return [
        ["ui-core", join(ROOT, "pxt_modules", "ui-core", "locales", lang + ".json")],
        ["ui-controls", join(ROOT, "pxt_modules", "ui-controls", "locales", lang + ".json")],
        ["app", join(ROOT, "locales", lang + ".json")],
    ];
}

// Merge the catalog layers for a language into one table, later layers winning.
// Returns the merged table and per-layer info (count is null when the layer
// file is absent).
function mergeLayers(lang) {
    const merged = {};
    const layers = [];
    for (const [name, path] of layerPathsFor(lang)) {
        const cat = readCatalog(path);
        if (cat === null) {
            layers.push({ name, path, count: null });
            continue;
        }
        for (const k of Object.keys(cat)) merged[k] = cat[k];
        layers.push({ name, path, count: Object.keys(cat).length });
    }
    return { merged, layers };
}

function emitLocG(lang, table) {
    const keys = Object.keys(table).sort();
    const lines = [];
    lines.push("// Generated by scripts/locgen.mjs. Holds the one shipped language's");
    lines.push("// translation table.");
    lines.push("//");
    lines.push("// Transient build intermediate: locgen restores the default state of this");
    lines.push("// file after the run. Do not commit this generated table.");
    lines.push("// lang: " + lang);
    lines.push("namespace _loc {");
    const entries = keys.map(k => "        " + JSON.stringify(k) + ": " + JSON.stringify(table[k]));
    lines.push("    table = {");
    lines.push(entries.join(",\n"));
    lines.push("    }");
    lines.push("}");
    return lines.join("\n") + "\n";
}

function buildAndCopy(lang) {
    execSync("npx mkc build", { cwd: ROOT, stdio: "pipe" });
    if (!existsSync(HEX_DIR)) mkdirSync(HEX_DIR, { recursive: true });
    const dst = join(HEX_DIR, "microcode-v2." + lang + ".hex");
    copyFileSync(join(ROOT, "built", "binary.hex"), dst);
    return { dst, size: statSync(dst).size };
}

// --- per-language processing ------------------------------------------------

function processLanguage(lang) {
    const report = { lang };

    if (lang === "en") {
        writeFileSync(LOC_G_PATH, DEFAULT_LOC_G);
        const webIds = writeWebStrings(lang, null);
        console.log(`\n=== ${lang} ===`);
        console.log(`  web strings: assets/strings/en/tooltips.json (${webIds} ids)`);
        const built = buildAndCopy(lang);
        report.merged = 0;
        report.identityDropped = 0;
        report.font5Dropped = 0;
        report.glyphDropped = 0;
        report.lengthWarnings = 0;
        report.layers = ["(source strings, no catalog)"];
        report.hexPath = built.dst;
        report.hexSize = built.size;
        console.log("  source-string build (no translation table)");
        console.log(`  hex: ${built.dst} (${built.size} bytes)`);
        return report;
    }

    console.log(`\n=== ${lang} ===`);
    const { merged, layers } = mergeLayers(lang);
    const layersFound = [];
    for (const l of layers) {
        if (l.count === null) {
            console.log(`  layer ${l.name}: missing (${l.path})`);
            continue;
        }
        layersFound.push(l.name);
        console.log(`  layer ${l.name}: ${l.count} entries`);
    }
    const mergedCount = Object.keys(merged).length;

    const webIds = writeWebStrings(lang, merged);
    console.log(`  web strings: assets/strings/${lang}/tooltips.json (${webIds} ids)`);

    // Sample-name strings ship only in the web snapshot.
    const sampleOnly = sampleOnlySources();
    let sampleDropped = 0;
    for (const k of Object.keys(merged)) {
        if (sampleOnly.has(k)) {
            delete merged[k];
            sampleDropped++;
        }
    }

    // Drop identity entries (value === key): they only waste flash.
    let identityDropped = 0;
    for (const k of Object.keys(merged)) {
        if (merged[k] === k) {
            delete merged[k];
            identityDropped++;
        }
    }

    const cov = font8Coverage();

    // font5-context validation: strings the app renders in font5 (the tagline)
    // are validated against font5 coverage, not the build font. A translation
    // font5 cannot render is dropped so the runtime falls back to the source
    // string rather than drawing blank.
    const font5Keys = font5SrcStrings();
    const font5Cov = font5Coverage();
    let font5Dropped = 0;
    for (const k of Object.keys(merged)) {
        if (!font5Keys.has(k)) continue;
        const val = merged[k];
        const missing = [];
        for (const ch of val) {
            const cp = ch.codePointAt(0);
            if (cp < 33) continue;
            if (!font5Cov.has(cp)) missing.push(ch + " " + toHexCp(cp));
        }
        if (missing.length > 0) {
            delete merged[k];
            font5Dropped++;
            console.log(`  [font5] drop ${lang} key ${JSON.stringify(k)} (font5 tagline context): missing ${missing.join(", ")}`);
        }
    }

    // Glyph validation: drop entries whose translation contains codepoints the
    // target font cannot render. Codepoints below 33 are always acceptable.
    // font5-context keys are exempt: they were validated against font5 above.
    let glyphDropped = 0;
    for (const k of Object.keys(merged)) {
        if (font5Keys.has(k)) continue;
        const val = merged[k];
        const missing = [];
        for (const ch of val) {
            const cp = ch.codePointAt(0);
            if (cp < 33) continue;
            if (!cov.has(cp)) missing.push(ch + " " + toHexCp(cp));
        }
        if (missing.length > 0) {
            delete merged[k];
            glyphDropped++;
            console.log(`  [glyph] drop ${lang} key ${JSON.stringify(k)} (font8): missing ${missing.join(", ")}`);
        }
    }

    // Length warning (never drops): translated text much longer than source.
    let lengthWarnings = 0;
    for (const k of Object.keys(merged)) {
        const srcLen = Array.from(k).length;
        const transLen = Array.from(merged[k]).length;
        if (transLen > srcLen * 1.5 && transLen - srcLen > 3) {
            lengthWarnings++;
            console.log(`  [length] ${lang} key ${JSON.stringify(k)}: src ${srcLen} -> trans ${transLen} chars`);
        }
    }

    const finalCount = Object.keys(merged).length;

    // A language none of whose translations survive validation would ship an
    // image identical to the source-string build; skip it rather than emit a
    // pointless hex.
    if (finalCount === 0) {
        console.log(`  merged ${mergedCount}, sample-only ${sampleDropped}, identity-dropped ${identityDropped}, font5-dropped ${font5Dropped}, glyph-dropped ${glyphDropped}`);
        console.log("  no renderable translations; skipped (no hex built)");
        report.layers = layersFound;
        report.merged = mergedCount;
        report.identityDropped = identityDropped;
        report.font5Dropped = font5Dropped;
        report.glyphDropped = glyphDropped;
        report.lengthWarnings = lengthWarnings;
        report.table = 0;
        report.skipped = true;
        return report;
    }

    writeFileSync(LOC_G_PATH, emitLocG(lang, merged));

    const built = buildAndCopy(lang);

    console.log(`  merged ${mergedCount}, sample-only ${sampleDropped}, identity-dropped ${identityDropped}, font5-dropped ${font5Dropped}, glyph-dropped ${glyphDropped}, length-warnings ${lengthWarnings}, table ${finalCount}`);
    console.log(`  hex: ${built.dst} (${built.size} bytes)`);

    report.layers = layersFound;
    report.merged = mergedCount;
    report.identityDropped = identityDropped;
    report.font5Dropped = font5Dropped;
    report.glyphDropped = glyphDropped;
    report.lengthWarnings = lengthWarnings;
    report.table = finalCount;
    report.hexPath = built.dst;
    report.hexSize = built.size;
    return report;
}

// --- coverage ---------------------------------------------------------------

// The full set of source strings the app can localize: the union of the
// ui-core, ui-controls and app source catalogs (keys) with the tooltip source
// strings (values of locales/tooltips.json, excluding the N* sample ids).
function sourceInventory() {
    const set = new Set();
    const addKeys = path => {
        const cat = readCatalog(path);
        if (cat) for (const k of Object.keys(cat)) set.add(k);
    };
    addKeys(join(ROOT, "pxt_modules", "ui-core", "locales", "en.json"));
    addKeys(join(ROOT, "pxt_modules", "ui-controls", "locales", "en.json"));
    addKeys(join(ROOT, "locales", "en.json"));
    const tips = readCatalog(join(ROOT, "locales", "tooltips.json"));
    if (tips) {
        for (const id of Object.keys(tips)) {
            if (/^N\d+$/.test(id)) continue;
            set.add(tips[id]);
        }
    }
    return set;
}

function coverageLangs() {
    const langs = [];
    for (const f of readdirSync(join(ROOT, "locales"))) {
        if (!f.endsWith(".json")) continue;
        const name = f.slice(0, -5);
        if (name === "en" || name === "tooltips") continue;
        langs.push(name);
    }
    return langs;
}

function runCoverage(langArgs, verbose) {
    const inventory = Array.from(sourceInventory()).sort();
    const total = inventory.length;
    const langs = langArgs.length > 0 ? langArgs : coverageLangs();

    console.log("locgen coverage");
    console.log(`inventory: ${total} source strings`);

    const rows = [];
    const missingByLang = {};
    for (const lang of langs) {
        const { merged } = mergeLayers(lang);
        let translated = 0;
        const missing = [];
        for (const s of inventory) {
            if (Object.prototype.hasOwnProperty.call(merged, s)) translated++;
            else missing.push(s);
        }
        const pct = total === 0 ? 100 : (translated / total) * 100;
        rows.push({ lang, total, translated, missing: missing.length, pct });
        missingByLang[lang] = missing;
    }

    const head = ["lang", "total", "translated", "missing", "percent"];
    const cells = rows.map(r => [
        r.lang,
        String(r.total),
        String(r.translated),
        String(r.missing),
        r.pct.toFixed(1) + "%",
    ]);
    const widths = head.map((h, i) =>
        Math.max(h.length, ...cells.map(c => c[i].length)));
    const fmt = c => c.map((v, i) => v.padEnd(widths[i])).join("  ");
    console.log("");
    console.log(fmt(head));
    for (const c of cells) console.log(fmt(c));

    if (verbose) {
        for (const lang of langs) {
            const missing = missingByLang[lang];
            console.log(`\n--- ${lang}: ${missing.length} missing ---`);
            for (const s of missing) console.log("  " + s);
        }
    }
}

// --- main -------------------------------------------------------------------

function resolveLangs(args) {
    if (args.length > 0) return args;
    const langs = ["en"];
    for (const f of readdirSync(join(ROOT, "locales"))) {
        if (!f.endsWith(".json")) continue;
        const name = f.slice(0, -5);
        if (name === "en" || name === "tooltips") continue;
        langs.push(name);
    }
    return langs;
}

function main() {
    const argv = process.argv.slice(2);
    const coverage = argv.indexOf("--coverage") >= 0;
    const verbose = argv.indexOf("--verbose") >= 0;
    // --keep leaves the last language's generated loc.g.ts in place instead of
    // restoring the default state, for inspecting the emitted table and font.
    const keep = argv.indexOf("--keep") >= 0;
    const positional = argv.filter(a => !a.startsWith("--"));

    if (coverage) {
        runCoverage(positional, verbose);
        return;
    }

    const langs = resolveLangs(positional);
    console.log("locgen: " + langs.join(", "));

    const reports = [];
    let leaveModified = false;
    let failedLang = null;
    try {
        for (const lang of langs) {
            try {
                reports.push(processLanguage(lang));
            } catch (err) {
                // A build failure leaves loc.g.ts in place for debugging.
                leaveModified = true;
                failedLang = lang;
                const out = (err.stdout && err.stdout.toString()) || "";
                const errOut = (err.stderr && err.stderr.toString()) || "";
                console.error(`\nERROR building ${lang}: ${err.message}`);
                if (out) console.error(out.split("\n").slice(-25).join("\n"));
                if (errOut) console.error(errOut.split("\n").slice(-25).join("\n"));
                throw err;
            }
        }
    } finally {
        if (leaveModified) {
            console.error(`\nloc.g.ts left MODIFIED (last: ${failedLang}) for debugging; not restored.`);
        } else if (keep) {
            console.log("\nloc.g.ts left in place (--keep); not restored.");
        } else {
            writeFileSync(LOC_G_PATH, DEFAULT_LOC_G);
            console.log("\nloc.g.ts restored to default state.");
        }
    }

    // Summary table.
    console.log("\n=== summary ===");
    const head = ["lang", "merged", "identity", "font5", "glyph", "len-warn", "table", "hex bytes"];
    console.log(head.join("\t"));
    for (const r of reports) {
        console.log([
            r.lang,
            r.merged,
            r.identityDropped,
            r.font5Dropped === undefined ? "-" : r.font5Dropped,
            r.glyphDropped,
            r.lengthWarnings,
            r.table === undefined ? "-" : r.table,
            r.skipped ? "(skipped)" : r.hexSize,
        ].join("\t"));
    }
}

main();
