// Regenerates tooltips.ts from locales/tooltips.json.
//
// locales/tooltips.json is the single source of truth mapping each tooltip id
// to its source string. This generator emits the complete tooltips.ts:
//
//   - tooltipTable: every id except the N* sample-name ids, in tooltips.json
//     key order.
//   - tooltip(id) / resolveTooltip(id): unchanged lookup and localization.
//   - tooltip2tid(name): reverse map from source string to numeric tid, one
//     entry per T<n> id.
//
// Usage: node scripts/tooltipgen.mjs

import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const JSON_PATH = join(ROOT, "locales", "tooltips.json")
const TS_PATH = join(ROOT, "tooltips.ts")

const HEADER = `// English tooltip/caption catalog, keyed by the ids used throughout the app
// (for example "rule_up", "C0", "T14"). The keys and English values are derived
// from locales/tooltips.json and regenerated by scripts/tooltipgen.mjs.
//
// This file holds English source strings only. Translations live in _loc.table:
// resolveTooltip() runs the English string through ui.loc(), which returns the
// translation when a per-language build supplies a table, and the English string
// unchanged otherwise.
//
// The N* sample-name ids from locales/tooltips.json are excluded here; they are
// not resolved at runtime by any file in the pxt.json files list.`

function main() {
    const table = JSON.parse(readFileSync(JSON_PATH, "utf8"))
    const ids = Object.keys(table)

    const tableIds = ids.filter(id => !/^N\d+$/.test(id))
    const tidIds = ids.filter(id => /^T(\d+)$/.test(id))

    const out = []
    out.push(HEADER)
    out.push("namespace microcode {")
    out.push("    // English source strings keyed by tooltip id. English content does not")
    out.push("    // depend on _loc, so this literal is safe at module-init time. Localization")
    out.push("    // is applied only by resolveTooltip(), at call time.")
    out.push("    const tooltipTable: { [id: string]: string } = {")
    for (const id of tableIds) {
        out.push("        " + JSON.stringify(id) + ": " + JSON.stringify(table[id]) + ",")
    }
    out.push("    }")
    out.push("")
    out.push("    // Returns the English source string for an id, or \"\" for a missing or")
    out.push("    // falsy id.")
    out.push("    export function tooltip(id: string): string {")
    out.push("        if (!id) return \"\"")
    out.push("        const res = tooltipTable[id]")
    out.push("        if (res === undefined) return \"\"")
    out.push("        return res")
    out.push("    }")
    out.push("")
    out.push("    // Returns the localized tooltip string for an id. The English source is")
    out.push("    // looked up first, then run through ui.loc; an unknown id yields \"\" and is")
    out.push("    // never passed through loc.")
    out.push("    export function resolveTooltip(id: string): string {")
    out.push("        const src = tooltip(id)")
    out.push("        if (!src) return \"\"")
    out.push("        return ui.loc(src) // locstrings-ignore: catalogued via tooltips.json")
    out.push("    }")
    out.push("")
    out.push("    // Reverse map from English tooltip string to Tid. Used by web-only tooling")
    out.push("    // (mcparser.ts), which is excluded from the hardware build; the content is")
    out.push("    // English, mirroring the catalog above.")
    out.push("    export function tooltip2tid(id: string): number {")
    out.push("        let tid: number = undefined")
    out.push("        if (!id) return tid")
    for (const id of tidIds) {
        const n = parseInt(id.slice(1), 10)
        out.push("        else if (id === " + JSON.stringify(table[id]) + ") tid = " + n)
    }
    out.push("        return tid")
    out.push("    }")
    out.push("}")

    writeFileSync(TS_PATH, out.join("\n") + "\n")

    console.log(
        `tooltipgen: tooltipTable ${tableIds.length} entries, tooltip2tid ${tidIds.length} entries`,
    )
}

main()
